import argparse
import os
import logging

import numpy as np

from recovar import utils
from recovar.heterogeneity import heterogeneity_volume, locres

logger = logging.getLogger(__name__)


def center_of_mass(array):
    array = np.asarray(array)
    total_mass = np.sum(array)
    coords = np.indices(array.shape)
    com = [np.sum(coords[i] * array) / total_mass for i in range(array.ndim)]
    return tuple(com)


def nearest_point_index(point, points_list):
    point = np.asarray(point)
    points_array = np.asarray(points_list)
    distances = np.linalg.norm(points_array - point, axis=1)
    return np.argmin(distances)


def decide_subvolume_index_from_mask(mask, sampling_points):
    center_of_mass_mask = center_of_mass(mask)
    nearest_idx = nearest_point_index(center_of_mass_mask, sampling_points)
    return nearest_idx


def extract_image_subset(input_dir, output_path, subvolume_idx, mask, coordinate):
    if mask is not None:
        mask = utils.load_mrc(mask)
        coordinate = center_of_mass(mask)

    if coordinate is not None:
        params = utils.pickle_load(os.path.join(input_dir, "params.pkl"))
        grid_size = utils.load_mrc(os.path.join(input_dir, "local_resolution.mrc")).shape[0]
        sampling_points = (
            locres.get_sampling_points(
                grid_size, params["locres_sampling"], params["locres_maskrad"], params["voxel_size"]
            )
            + grid_size // 2
        )
        subvolume_idx = nearest_point_index(coordinate, sampling_points)
        logger.info(
            "Extract images for feature at coordinate = %s (pixels), Nearest point to the coordinate is %s",
            coordinate,
            subvolume_idx,
        )

    good_indices = heterogeneity_volume.get_inds_for_subvolume(input_dir, subvolume_idx)
    logger.info("Found %s images. Saving indices of subset of images", good_indices.size)
    utils.pickle_dump(good_indices, output_path)


def main():
    parser = argparse.ArgumentParser(description="Extract a subset of images from a directory")
    parser.add_argument(
        "input_dir",
        type=os.path.abspath,
        help="A path to a folder generated by one of the scripts that makes volumes (analyze, compute_state, compute_trajectory)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=os.path.abspath,
        help="output path to a .pkl file containing the indices of subset of images",
    )
    parser.add_argument("-s", "--subvol-idx", dest="subvol_idx", type=int, help="Which subvolume is used")
    parser.add_argument(
        "--mask",
        metavar="mrc",
        default=None,
        help="Small mask around the feature for which you want images. Equivalent to providing the coordinate of the center of mass of the mask.",
    )

    def list_of_ints(arg):
        return list(map(int, arg.split(",")))

    parser.add_argument(
        "--coordinate",
        default=None,
        dest="coordinate",
        type=list_of_ints,
        help="Coordinate in pixel of the feature for which you want images. E.g. 20,30,50",
    )
    from recovar.utils.parser_args import add_project_arg

    add_project_arg(parser)

    args = parser.parse_args()
    if args.subvol_idx is None and args.mask is None and args.coordinate is None:
        raise ValueError("You need to provide either a subvolume index, a mask or a coordinate")
    if args.subvol_idx is not None and (args.mask is not None or args.coordinate is not None):
        raise ValueError("You need to provide only one of subvolume index, mask or coordinate")

    from recovar.project.job_context import job_context

    with job_context(args, "extract_image_subset") as ctx:
        args.output = ctx.output_dir
        extract_image_subset(args.input_dir, args.output, args.subvol_idx, args.mask, args.coordinate)


if __name__ == "__main__":
    main()
