"""Core cryo-EM primitives: indexing, geometry, CTF, slicing, and forward model.

Re-exports public symbols from submodules so that ``from recovar import core``
and ``core.translate_images(...)`` etc. continue to work unchanged.
"""

from recovar.core.geometry import (
    batch_batch_find_frequencies_within_grid_dist,
    batch_find_frequencies_within_grid_dist,
    batch_get_gridpoint_coords,
    batch_get_nearest_gridpoint_indices,
    batch_trans_translate_images,
    batch_translate,
    find_frequencies_within_grid_dist,
    get_gridpoint_coords,
    get_nearest_gridpoint_indices,
    get_stencil,
    get_unrotated_plane_coords,
    get_unrotated_plane_grid_points,
    rotations_to_grid_point_coords,
    round_to_int,
    translate_images,
    translate_single_image,
)
from recovar.core.indexing import (
    check_frequencies_in_bound,
    check_vec_indices_in_bound,
    check_vol_indices_in_bound,
    distance_to_max_grid_dist,
    frequencies_to_vec_indices,
    frequencies_to_vol_indices,
    vec_indices_to_frequencies,
    vec_indices_to_vol_indices,
    vol_indices_to_frequencies,
    vol_indices_to_vec_indices,
)
from recovar.core.ctf import (
    CTFEvaluator,
    CTFMode,
    CTFParamIndex,
    as_ctf_evaluator,
    batch_evaluate_ctf,
    critical_exposure,
    evaluate_ctf,
    evaluate_ctf_packed,
    get_dose_filters,
    get_dose_filters_from_tilt_number,
)
from recovar.core.configs import BatchData, DataIterator, ForwardModelConfig
from recovar.core.forward import (
    batch_translate_images,
)
from recovar.core.slicing import (
    _AUTO,
    _default_max_r,
    adjoint_slice_volume,
    batch_adjoint_slice_volume,
    batch_slice_volume,
    decide_order,
    precompute_cubic_coefficients,
    precompute_cubic_coefficients_half,
    slice_from_cubic_coefficients,
    slice_volume,
)

__all__ = [
    "BatchData",
    "CTFEvaluator",
    "CTFMode",
    "CTFParamIndex",
    "as_ctf_evaluator",
    "adjoint_slice_volume",
    "batch_batch_find_frequencies_within_grid_dist",
    "batch_evaluate_ctf",
    "batch_find_frequencies_within_grid_dist",
    "batch_get_gridpoint_coords",
    "batch_get_nearest_gridpoint_indices",
    "batch_adjoint_slice_volume",
    "batch_slice_volume",
    "batch_trans_translate_images",
    "batch_translate",
    "batch_translate_images",
    "check_frequencies_in_bound",
    "check_vec_indices_in_bound",
    "check_vol_indices_in_bound",
    "critical_exposure",
    "DataIterator",
    "decide_order",
    "distance_to_max_grid_dist",
    "evaluate_ctf",
    "evaluate_ctf_packed",
    "find_frequencies_within_grid_dist",
    "ForwardModelConfig",
    "frequencies_to_vec_indices",
    "frequencies_to_vol_indices",
    "get_dose_filters",
    "get_dose_filters_from_tilt_number",
    "get_gridpoint_coords",
    "get_nearest_gridpoint_indices",
    "get_stencil",
    "get_unrotated_plane_coords",
    "get_unrotated_plane_grid_points",
    "precompute_cubic_coefficients",
    "precompute_cubic_coefficients_half",
    "rotations_to_grid_point_coords",
    "round_to_int",
    "slice_from_cubic_coefficients",
    "slice_volume",
    "translate_images",
    "translate_single_image",
    "vec_indices_to_frequencies",
    "vec_indices_to_vol_indices",
    "vol_indices_to_frequencies",
    "vol_indices_to_vec_indices",
]
