"""Compatibility facade that re-exports recovar core primitives.

This module preserves the historical `recovar.core.*` import surface while
the implementation lives in focused submodules:
- `core_indexing`
- `core_geometry`
- `core_slicing`
- `core_ctf`
- `core_forward`
"""

from recovar.core_geometry import (
    batch_batch_find_frequencies_within_grid_dist,
    batch_find_frequencies_within_grid_dist,
    batch_get_gridpoint_coords,
    batch_get_nearest_gridpoint_indices,
    batch_trans_translate_images,
    batch_translate,
    find_frequencies_within_grid_dist,
    get_gridpoint_coords,
    get_nearest_gridpoint_indices,
    get_stencil,
    get_unrotated_plane_coords,
    get_unrotated_plane_grid_points,
    rotations_to_grid_point_coords,
    round_to_int,
    translate_images,
    translate_single_image,
)
from recovar.core_indexing import (
    check_frequencies_in_bound,
    check_vec_indices_in_bound,
    check_vol_indices_in_bound,
    distance_to_max_grid_dist,
    frequencies_to_vec_indices,
    frequencies_to_vol_indices,
    vec_indices_to_frequencies,
    vec_indices_to_vol_indices,
    vol_indices_to_frequencies,
    vol_indices_to_vec_indices,
)
from recovar.core_ctf import (
    CTFParamIndex,
    CTFParams,
    batch_evaluate_ctf,
    critical_exposure,
    cryodrgn_CTF,
    evaluate_ctf,
    evaluate_ctf_packed,
    evaluate_ctf_wrapper,
    evaluate_ctf_wrapper_half,
    evaluate_ctf_wrapper_tilt_series,
    evaluate_ctf_wrapper_tilt_series_half,
    evaluate_ctf_wrapper_tilt_series_v2,
    evaluate_ctf_wrapper_tilt_series_v2_half,
    get_cryo_ET_CTF_fun,
    get_cryo_ET_CTF_fun_half,
    get_dose_filters,
    get_dose_filters_from_tilt_number,
    cryodrgn_CTF_half,
)
from recovar.core_forward import (
    adjoint_forward_model_from_map,
    adjoint_forward_model_from_trilinear,
    batch_forward_model_from_map,
    batch_translate_images,
    compute_A_t_Av_forward_model_from_map,
    forward_model_from_map,
    forward_model_from_map_and_return_adjoint,
)
from recovar.core_slicing import (
    adjoint_slice_volume_by_map,
    adjoint_slice_volume_by_map_from_half_images_to_half_volume,
    adjoint_slice_volume_by_trilinear,
    adjoint_slice_volume_by_trilinear_from_half_images_to_half_volume,
    adjoint_slice_volume_by_trilinear_from_weights,
    batch_over_vol_summed_adjoint_slice_by_nearest,
    batch_slice_volume_by_nearest,
    decide_order,
    forward_model,
    forward_model_from_half_ctf,
    get_trilinear_weights_and_vol_indices,
    map_coordinates_on_slices,
    nosummed_adjoint_slice_by_nearest,
    split_full_plane_indices_for_half,
    slice_volume_by_map,
    slice_volume_by_nearest,
    slice_volume_by_trilinear,
    sum_adj_forward_model,
    sum_adj_forward_model_from_half,
    sum_adj_forward_model_from_half_to_half,
    summed_adjoint_slice_by_nearest,
)

__all__ = [
    "CTFParamIndex",
    "CTFParams",
    "adjoint_forward_model_from_map",
    "adjoint_forward_model_from_trilinear",
    "adjoint_slice_volume_by_map",
    "adjoint_slice_volume_by_map_from_half_images_to_half_volume",
    "adjoint_slice_volume_by_trilinear",
    "adjoint_slice_volume_by_trilinear_from_half_images_to_half_volume",
    "adjoint_slice_volume_by_trilinear_from_weights",
    "batch_batch_find_frequencies_within_grid_dist",
    "batch_evaluate_ctf",
    "batch_find_frequencies_within_grid_dist",
    "batch_forward_model_from_map",
    "batch_get_gridpoint_coords",
    "batch_get_nearest_gridpoint_indices",
    "batch_over_vol_summed_adjoint_slice_by_nearest",
    "batch_slice_volume_by_nearest",
    "batch_trans_translate_images",
    "batch_translate",
    "batch_translate_images",
    "check_frequencies_in_bound",
    "check_vec_indices_in_bound",
    "check_vol_indices_in_bound",
    "compute_A_t_Av_forward_model_from_map",
    "critical_exposure",
    "cryodrgn_CTF",
    "decide_order",
    "distance_to_max_grid_dist",
    "evaluate_ctf",
    "evaluate_ctf_packed",
    "evaluate_ctf_wrapper",
    "evaluate_ctf_wrapper_half",
    "evaluate_ctf_wrapper_tilt_series",
    "evaluate_ctf_wrapper_tilt_series_half",
    "evaluate_ctf_wrapper_tilt_series_v2",
    "evaluate_ctf_wrapper_tilt_series_v2_half",
    "find_frequencies_within_grid_dist",
    "forward_model",
    "forward_model_from_half_ctf",
    "forward_model_from_map",
    "forward_model_from_map_and_return_adjoint",
    "frequencies_to_vec_indices",
    "frequencies_to_vol_indices",
    "get_cryo_ET_CTF_fun",
    "get_cryo_ET_CTF_fun_half",
    "get_dose_filters",
    "get_dose_filters_from_tilt_number",
    "get_gridpoint_coords",
    "get_nearest_gridpoint_indices",
    "get_stencil",
    "get_trilinear_weights_and_vol_indices",
    "get_unrotated_plane_coords",
    "get_unrotated_plane_grid_points",
    "map_coordinates_on_slices",
    "nosummed_adjoint_slice_by_nearest",
    "rotations_to_grid_point_coords",
    "round_to_int",
    "split_full_plane_indices_for_half",
    "slice_volume_by_map",
    "slice_volume_by_nearest",
    "slice_volume_by_trilinear",
    "sum_adj_forward_model",
    "sum_adj_forward_model_from_half",
    "sum_adj_forward_model_from_half_to_half",
    "summed_adjoint_slice_by_nearest",
    "cryodrgn_CTF_half",
    "translate_images",
    "translate_single_image",
    "vec_indices_to_frequencies",
    "vec_indices_to_vol_indices",
    "vol_indices_to_frequencies",
    "vol_indices_to_vec_indices",
]
